[profile.default]
ffi = true
ast = true
build_info = true
src = "src"
out = "out"
libs = ["lib"]
extra_output = ["storageLayout"]
solc_version = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
