[profile.default]
ffi = true
ast = true
build_info = true
src = "src"
out = "out"
libs = ["lib"]
extra_output = ["storageLayout"]
solc_version = "0.8.26"
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/viXU37kdp6nJVji10bu7WkqYqT4teCkL"
avalanche = "https://long-light-pond.avalanche-testnet.quiknode.pro/35cbf62e2590b9cb8c2237bbef17157703025192/ext/bc/C/rpc/"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
